import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>聚合点餐</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="https://h5.lantu7.cn" className={styles.card}>
            <h2>团小淘&nbsp;&nbsp;&nbsp;&rarr;</h2>
          </a>

          <a href="https://mt.jzybox.com" className={styles.card}>
            <h2>撸餐&nbsp;&nbsp;&nbsp;&nbsp;&rarr;</h2>
          </a>

          <a
            href="https://gw.djtaoke.cn"
            className={styles.card}
          >
            <h2>小蚕芸 &rarr;</h2>
          </a>

          <a
            href="https://bwc.jiulingtech.tech"
            className={styles.card}
          >
            <h2>霸王慧 &rarr;</h2>
          </a>

          <a
              href="https://www.nbjiazhi.top"
              className={styles.card}
          >
            <h2>饱饱生活圈 &rarr;</h2>
          </a>

          <a
              href="https://www.xxh-life.com"
              className={styles.card}
          >
            <h2>晓晓优选 &rarr;</h2>
          </a>

          <a
              href="https://h5.bchibhe.com"
              className={styles.card}
          >
            <h2>白吃白喝 &rarr;</h2>
          </a>

          <a
              href="https://vip.cchll.cn"
              className={styles.card}
          >
            <h2>吃撑黄绿蓝 &rarr;</h2>
          </a>

          <a
              href="https://m.bwyc168.com"
              className={styles.card}
          >
            <h2>霸王用餐CQ &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
